### ISSUE TITLE
Error while running test_basic_class.py

### ISSUE THREAD

**Issue by gopalkriagg** [JFF-Bohdan/sim-module#5]
$: python test_basic_class.py 
Traceback (most recent call last):
  File "test_basic_class.py", line 3, in <module>
    from test_shared import *
  File "/root/istp_prototype/sim-module/test_shared.py", line 4, in <module>
    from lib.sim900.gsm import SimGsm, SimGsmPinRequestState
  File "/root/istp_prototype/sim-module/lib/sim900/gsm.py", line 114
    def print(self, commandString, encoding = "ascii"):
            ^
SyntaxError: invalid syntax

Why is this error coming?

**Comment by JFF-Bohdan** [comment]
Do you use Python3?
